feat: detect and support window.ipfs.enable experiment
ipfs-shipyard/window.ipfs-fallback pull request #2
Opened 2018-11-14 13:57 UTC by lidel

Just to get the ball rolling, this PR adds a simple heuristic for forward-compatible detection of IPFS API exposed by experimental branch of ipfs-companion: https://github.com/ipfs-shipyard/ipfs-companion/issues/589

@alanshaw I can take care of releasing this if you make me a colaborator on NPM.

2018-11-16 15:13 UTC, alanshaw requested changes
Code LGTM - would you mind adding a test?

2018-11-16 15:13 UTC, alanshaw commented on index.js
> +        return resolve(window.ipfs.enable())
Pass wanted permissions...so we don't have to do another release??

```suggestion
        return resolve(window.ipfs.enable(opts.permissions))
```

2018-11-17 21:36 UTC, lidel commented
@alanshaw done, check now:
- added test
- added support for overriding `defaults`
  - did not want to name it 'permissions` as we may want to pass other flags

2018-11-19 14:30 UTC, alanshaw commented
> - added support for overriding `defaults`

hmm, I don't expect to pass "defaults" normally! It suggests something is going to override them...when actually what I pass would usually override anything set by default.

>   - did not want to name it 'permissions` as we may want to pass other flags 

Unless you have something in mind right now I'd suggest sticking to `permissions` (we know we want that) and change it when we want to pass something else/more.

2018-11-19 14:48 UTC, lidel commented
@alanshaw lets go with `permissions` for now (https://github.com/ipfs-shipyard/window.ipfs-fallback/pull/2/commits/bed7c7206f0dd8ffaee18ada8f5bfd4bc49cab03)

2018-11-19 14:53 UTC, alanshaw approved these changes

2018-11-19 14:53 UTC, merged